[book]
title = "cc-viewer Manual"
authors = ["jhhuh"]
language = "en"
src = "src"

[build]
build-dir = "book"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/jhhuh/cc-viewer"
